#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / "upstream" / "stockfish"
OVERLAY = ROOT / "src" / "stockless"
DEFAULT_OUT = ROOT / "build" / "stockless-src"

STOCKFISH_SHA = "0a215d6c9e48856ef630013b8ab8312941a59057"
RECKLESS_SHA = "31d9cd6fd2bea6d9f72eeb35e0bac70daa295fb1"


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected exactly one patch anchor, found {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def ensure_submodules() -> None:
    if (UPSTREAM / "src" / "search.cpp").exists():
        return
    subprocess.run(
        ["git", "submodule", "update", "--init", "--recursive"],
        cwd=ROOT,
        check=True,
    )


def verify_pin() -> None:
    actual = subprocess.check_output(
        ["git", "-C", str(UPSTREAM), "rev-parse", "HEAD"],
        text=True,
    ).strip()
    if actual != STOCKFISH_SHA:
        raise RuntimeError(
            f"Stockfish submodule is {actual}, expected pinned {STOCKFISH_SHA}. "
            "Update docs/UPSTREAM.md and patch anchors before changing the pin."
        )


def materialize(out: Path) -> None:
    ensure_submodules()
    verify_pin()

    if out.exists():
        shutil.rmtree(out)

    shutil.copytree(
        UPSTREAM,
        out,
        ignore=shutil.ignore_patterns(".git"),
    )

    target_overlay = out / "src" / "stockless"
    shutil.copytree(OVERLAY, target_overlay)

    search_cpp = out / "src" / "search.cpp"
    engine_cpp = out / "src" / "engine.cpp"

    replace_once(
        search_cpp,
        '#include "search.h"\n',
        '#include "search.h"\n#include "stockless/search_policy.h"\n',
    )

    reduction_anchor = "        int r = reduction(improving, depth, moveCount, delta);\n"
    reduction_patch = reduction_anchor + """
        const auto stocklessPolicy = Stockless::make_search_policy({
          int(depth),
          moveCount,
          delta,
          ss->staticEval == VALUE_NONE ? 0 : int(ss->staticEval),
          int(alpha),
          int(beta),
          improving,
          capture,
          givesCheck,
          ss->inCheck,
          ss->ttPv,
        });
        r += stocklessPolicy.lmrAdjustment;
"""
    replace_once(search_cpp, reduction_anchor, reduction_patch)

    replace_once(
        engine_cpp,
        '#include "search.h"\n',
        '#include "search.h"\n#include "stockless/config.h"\n',
    )

    option_anchor = '    options.add("UCI_ShowWDL", Option(false));\n'
    option_patch = option_anchor + """
    options.add(
      "StocklessHybrid", Option(false, [](const Option& o) {
          Stockless::set_hybrid_enabled(bool(o));
          return std::nullopt;
      }));

    options.add(
      "StocklessAggression", Option(100, 0, 200, [](const Option& o) {
          Stockless::set_hybrid_aggression(int(o));
          return std::nullopt;
      }));
"""
    replace_once(engine_cpp, option_anchor, option_patch)

    marker = out / "STOCKLESS_MATERIALIZED.txt"
    marker.write_text(
        "Generated by tools/materialize.py\n"
        f"Stockfish: {STOCKFISH_SHA}\n"
        f"Reckless reference: {RECKLESS_SHA}\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    materialize(args.out.resolve())
    print(args.out.resolve())


if __name__ == "__main__":
    main()
